markdownExploder: true
prd:
  prdFile: docs/prd.md
  prdVersion: v4
  prdSharded: true
  prdShardedLocation: docs/prd
  epicFilePattern: epic-{n}*.md
architecture:
  architectureFile: docs/architecture.md
  architectureVersion: v4
  architectureSharded: true
  architectureShardedLocation: docs/architecture
epics:
  epicsFile: docs/epics-and-stories.md
  epicsSharded: true
  epicsShardedLocation: docs/epics
uiDesignSystem:
  designSystemFile: docs/UI-DESIGN-SYSTEM.md
  designSystemSharded: true
  designSystemShardedLocation: docs/ui-design-system
customTechnicalDocuments: null
devLoadAlwaysFiles:
  - docs/architecture/coding-standards.md
  - docs/architecture/tech-stack.md
  - docs/architecture/source-tree.md
devDebugLog: .ai/debug-log.md
devStoryLocation: docs/stories
slashPrefix: BMad
